// Auto-generated by Supabase CLI — do not hand-edit
// Run: supabase gen types typescript --project-id <id> --schema public > src/types/database.ts

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
