// Auto-generated by Supabase CLI — do not hand-edit
// Run: supabase gen types typescript --project-id fwzltthkcwthuuptqlby --schema public > src/types/database.ts
// Last synced: 2026-06-25 (utm_templates, utm_history)

export type Database = {
  public: {
    Tables: {
      utm_templates: {
        Row: {
          id: string
          user_id: string
          name: string
          source: string | null
          medium: string | null
          campaign: string | null
          content: string | null
          term: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          source?: string | null
          medium?: string | null
          campaign?: string | null
          content?: string | null
          term?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          source?: string | null
          medium?: string | null
          campaign?: string | null
          content?: string | null
          term?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'utm_templates_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      utm_history: {
        Row: {
          id: string
          user_id: string
          template_id: string | null
          base_url: string
          source: string
          medium: string
          campaign: string
          content: string | null
          term: string | null
          generated_url: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          template_id?: string | null
          base_url: string
          source: string
          medium: string
          campaign: string
          content?: string | null
          term?: string | null
          generated_url: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          template_id?: string | null
          base_url?: string
          source?: string
          medium?: string
          campaign?: string
          content?: string | null
          term?: string | null
          generated_url?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'utm_history_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'utm_history_template_id_fkey'
            columns: ['template_id']
            isOneToOne: false
            referencedRelation: 'utm_templates'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
